import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const RESEND_API_KEY = process.env.RESEND_API_KEY
const resend = RESEND_API_KEY && !RESEND_API_KEY.includes('PLACEHOLDER') ? new Resend(RESEND_API_KEY) : null

const TEAM_EMAIL = 'dayma.itamunoala@colliers.com'
const CC_EMAIL = 'd.itamuno@gmail.com'
const FROM_EMAIL = 'OnMultifamily <noreply@onmultifamily.com>'

function formatCurrency(val: number): string {
  return new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD', maximumFractionDigits: 0 }).format(val)
}

function formatPercent(val: number, decimals = 2): string {
  return `${val.toFixed(decimals)}%`
}

function buildUserEmail(data: any): string {
  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Your CMHC Debt Sizing Analysis</title>
</head>
<body style="margin:0;padding:0;background:#f8f7f4;font-family:Georgia,'Times New Roman',serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f7f4;">
<tr><td align="center" style="padding:40px 20px;">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #e8e5df;">

<!-- Header -->
<tr><td style="background:#1a2332;padding:32px 40px;">
  <h1 style="margin:0;color:#ffffff;font-size:24px;font-weight:400;letter-spacing:-0.5px;">CMHC Debt Sizing Analysis</h1>
  <p style="margin:8px 0 0;color:rgba(255,255,255,0.4);font-size:13px;font-family:Arial,sans-serif;">Generated by OnMultifamily.com</p>
</td></tr>

<!-- Primary Result -->
<tr><td style="padding:32px 40px;border-bottom:1px solid #e8e5df;">
  <p style="margin:0 0 4px;color:#c4a35a;font-size:11px;font-family:Arial,sans-serif;text-transform:uppercase;letter-spacing:2px;">Maximum Insured Loan</p>
  <p style="margin:0 0 8px;color:#1a2332;font-size:36px;font-weight:400;">${formatCurrency(data.results.maxLoan)}</p>
  <p style="margin:0;color:#1a2332;opacity:0.4;font-size:13px;font-family:Arial,sans-serif;">
    Constrained by ${data.results.bindingConstraint} · ${formatPercent(data.results.actualLTV * 100, 1)} LTV · ${formatPercent(data.results.contractRate)} rate
  </p>
</td></tr>

<!-- Deal Summary -->
<tr><td style="padding:24px 40px;border-bottom:1px solid #e8e5df;">
  <h3 style="margin:0 0 16px;color:#1a2332;font-size:16px;font-weight:400;">Deal Summary</h3>
  <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,sans-serif;font-size:13px;">
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Property</td><td align="right" style="padding:6px 0;color:#1a2332;">${data.inputs.units} units · ${data.inputs.constructionType === 'wood' ? 'Wood Frame' : 'Concrete'}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Avg. Rent</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.inputs.avgMonthlyRentPerUnit)}/unit/mo</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Lending Value</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.lendingValue)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Cap Rate</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatPercent(data.results.capRate)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Price Per Unit</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.pricePerUnit)}</td></tr>
  </table>
</td></tr>

<!-- NOI -->
<tr><td style="padding:24px 40px;border-bottom:1px solid #e8e5df;">
  <h3 style="margin:0 0 16px;color:#1a2332;font-size:16px;font-weight:400;">Net Operating Income</h3>
  <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,sans-serif;font-size:13px;">
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Gross Potential Income</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.grossPotentialIncome)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Effective Gross Income</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.egi)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Total Expenses</td><td align="right" style="padding:6px 0;color:#1a2332;">(${formatCurrency(data.results.totalExpenses)})</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Expense Ratio</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatPercent(data.results.expenseRatio)}</td></tr>
    <tr><td colspan="2" style="padding:8px 0 0;border-top:1px solid #e8e5df;"></td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;font-weight:600;">Net Operating Income</td><td align="right" style="padding:6px 0;color:#1a2332;font-weight:600;font-size:16px;">${formatCurrency(data.results.noi)}</td></tr>
  </table>
</td></tr>

<!-- Debt Sizing -->
<tr><td style="padding:24px 40px;border-bottom:1px solid #e8e5df;">
  <h3 style="margin:0 0 16px;color:#1a2332;font-size:16px;font-weight:400;">Debt Sizing</h3>
  <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,sans-serif;font-size:13px;">
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">DSCR-Sized Loan</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.dscrMaxLoan)} ${data.results.bindingConstraint === 'DSCR' ? '(BINDING)' : ''}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">LTV-Sized Loan</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.ltvMaxLoan)} ${data.results.bindingConstraint === 'LTV' ? '(BINDING)' : ''}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">CMHC Insurance Premium</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.insurancePremium)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Total Insured Loan</td><td align="right" style="padding:6px 0;color:#1a2332;font-weight:600;">${formatCurrency(data.results.totalInsuredLoan)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Annual Debt Service</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatCurrency(data.results.annualDS)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Actual DSCR</td><td align="right" style="padding:6px 0;color:#1a2332;">${data.results.actualDSCR.toFixed(2)}x</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Contract Rate</td><td align="right" style="padding:6px 0;color:#1a2332;">${formatPercent(data.results.contractRate)} (CMB ${formatPercent(data.inputs.cmbYield)} + ${formatPercent(data.inputs.lenderSpread)} spread)</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Amortization</td><td align="right" style="padding:6px 0;color:#1a2332;">${data.results.effectiveAmort} years</td></tr>
  </table>
</td></tr>

<!-- Returns -->
<tr><td style="padding:24px 40px;border-bottom:1px solid #e8e5df;">
  <h3 style="margin:0 0 16px;color:#1a2332;font-size:16px;font-weight:400;">Returns</h3>
  <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,sans-serif;font-size:13px;">
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">${data.inputs.loanPurpose === 'purchase' ? 'Equity Required' : 'Equity Extraction'}</td><td align="right" style="padding:6px 0;color:#1a2332;font-weight:600;">${formatCurrency(data.inputs.loanPurpose === 'purchase' ? data.results.equityRequired : data.results.equityExtraction)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Year 1 Cash Flow</td><td align="right" style="padding:6px 0;color:${data.results.cashFlow >= 0 ? '#22c55e' : '#ef4444'};">${formatCurrency(data.results.cashFlow)}</td></tr>
    <tr><td style="padding:6px 0;color:#1a2332;opacity:0.5;">Cash-on-Cash Return</td><td align="right" style="padding:6px 0;color:${data.results.cashOnCash >= 0 ? '#22c55e' : '#ef4444'};">${formatPercent(data.results.cashOnCash)}</td></tr>
  </table>
</td></tr>

<!-- CTA -->
<tr><td style="padding:32px 40px;text-align:center;">
  <p style="margin:0 0 16px;color:#1a2332;font-size:16px;">Need a lender-ready underwriting?</p>
  <p style="margin:0 0 20px;color:#1a2332;opacity:0.4;font-size:13px;font-family:Arial,sans-serif;">Our team can run a full underwriting with market-specific adjustments for your property.</p>
  <a href="https://onmultifamily.com/#contact" style="display:inline-block;background:#1a2332;color:#ffffff;text-decoration:none;padding:12px 32px;font-size:12px;font-family:Arial,sans-serif;text-transform:uppercase;letter-spacing:2px;">Contact Our Team</a>
</td></tr>

<!-- Footer -->
<tr><td style="padding:24px 40px;background:#f8f7f4;border-top:1px solid #e8e5df;">
  <p style="margin:0;color:#1a2332;opacity:0.3;font-size:11px;font-family:Arial,sans-serif;text-align:center;">
    This analysis is for informational purposes only and does not constitute a loan commitment, pre-approval, or financial advice. 
    Actual CMHC-insured loan terms, premiums, and eligibility are subject to lender and CMHC underwriting review. 
    Contact a licensed mortgage professional for property-specific advice.
  </p>
  <p style="margin:12px 0 0;color:#1a2332;opacity:0.2;font-size:11px;font-family:Arial,sans-serif;text-align:center;">
    OnMultifamily.com · Colliers International · Toronto, Ontario
  </p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`
}

function buildTeamEmail(data: any): string {
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f8f7f4;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f7f4;">
<tr><td align="center" style="padding:40px 20px;">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #e8e5df;">

<tr><td style="background:#1a2332;padding:24px 32px;">
  <h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:400;">New Calculator Lead</h1>
</td></tr>

<tr><td style="padding:24px 32px;border-bottom:1px solid #e8e5df;">
  <h3 style="margin:0 0 12px;color:#1a2332;font-size:14px;">Contact Info</h3>
  <table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;">
    <tr><td style="padding:4px 0;color:#666;">Name</td><td style="padding:4px 0;color:#1a2332;font-weight:600;">${data.contact.name}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Email</td><td style="padding:4px 0;color:#1a2332;font-weight:600;"><a href="mailto:${data.contact.email}">${data.contact.email}</a></td></tr>
    ${data.contact.phone ? `<tr><td style="padding:4px 0;color:#666;">Phone</td><td style="padding:4px 0;color:#1a2332;font-weight:600;">${data.contact.phone}</td></tr>` : ''}
  </table>
</td></tr>

<tr><td style="padding:24px 32px;border-bottom:1px solid #e8e5df;">
  <h3 style="margin:0 0 12px;color:#1a2332;font-size:14px;">Their Analysis</h3>
  <table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;">
    <tr><td style="padding:4px 0;color:#666;">Units</td><td style="padding:4px 0;">${data.inputs.units}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Construction</td><td style="padding:4px 0;">${data.inputs.constructionType}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Purpose</td><td style="padding:4px 0;">${data.inputs.loanPurpose}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Avg. Rent</td><td style="padding:4px 0;">${formatCurrency(data.inputs.avgMonthlyRentPerUnit)}/unit</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Lending Value</td><td style="padding:4px 0;">${formatCurrency(data.results.lendingValue)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Cap Rate</td><td style="padding:4px 0;">${formatPercent(data.results.capRate)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">NOI</td><td style="padding:4px 0;">${formatCurrency(data.results.noi)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Max Loan</td><td style="padding:4px 0;font-weight:600;">${formatCurrency(data.results.maxLoan)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Binding Constraint</td><td style="padding:4px 0;">${data.results.bindingConstraint}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">LTV</td><td style="padding:4px 0;">${formatPercent(data.results.actualLTV * 100, 1)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">DSCR</td><td style="padding:4px 0;">${data.results.actualDSCR.toFixed(2)}x</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Rate</td><td style="padding:4px 0;">${formatPercent(data.results.contractRate)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Equity Required</td><td style="padding:4px 0;">${formatCurrency(data.results.equityRequired)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">Cash-on-Cash</td><td style="padding:4px 0;">${formatPercent(data.results.cashOnCash)}</td></tr>
    <tr><td style="padding:4px 0;color:#666;">MLI Select</td><td style="padding:4px 0;">${data.inputs.mliSelect ? `Yes (${data.inputs.mliCredits} credits)` : 'No'}</td></tr>
  </table>
</td></tr>

<tr><td style="padding:16px 32px;background:#f8f7f4;">
  <p style="margin:0;color:#999;font-size:11px;">Sent from CMHC Calculator at onmultifamily.com · ${new Date().toISOString()}</p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`
}

export async function POST(request: NextRequest) {
  try {
    const data = await request.json()
    
    const { contact, inputs, results } = data
    
    if (!contact?.name || !contact?.email) {
      return NextResponse.json({ error: 'Name and email are required' }, { status: 400 })
    }

    // Basic email validation
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
    }

    if (!resend) {
      return NextResponse.json({ error: 'Email service is currently unavailable. Please contact us directly.' }, { status: 503 })
    }

    // Send to user
    await resend.emails.send({
      from: FROM_EMAIL,
      to: contact.email,
      subject: `Your CMHC Debt Sizing: ${formatCurrency(results.maxLoan)} on ${inputs.units} units`,
      html: buildUserEmail(data),
    })

    // Send to team
    await resend.emails.send({
      from: FROM_EMAIL,
      to: TEAM_EMAIL,
      cc: CC_EMAIL,
      subject: `[Calculator Lead] ${contact.name} - ${inputs.units} units, ${formatCurrency(results.maxLoan)}`,
      html: buildTeamEmail(data),
    })

    return NextResponse.json({ success: true })
  } catch (error: any) {
    console.error('Calculator email error:', error)
    return NextResponse.json(
      { error: 'Failed to send email. Please try again.' },
      { status: 500 }
    )
  }
}
